### ISSUE TITLE
How to integrate in existing web app written in Java and Java script.

### ISSUE THREAD

**Issue by atiqq122** [NeoSmartpen/Windows-SDK2.0#11]
How to integrate in existing web app written in Java and Java script. 
Is any support or sdk for java developers or java script library to provide the support of the smart pen in existing web app.

**Comment by chyccs** [comment]
hi atiqq122,
Thanks for using our product.
We don't have library for java platform.
Because our product designed for mobile and desktop platform (can use bluetooth).
We also think that necessary of java platform.
Currently we have some material for integrate with web application (using javascript).
But we need to check it can help you. and its perfection.
So if you really want to get it, please comment in this issue.

Thanks

**Comment by atiqq122** [comment]
Hey @chyccs  appreciates your response . if is does support Java script I will be best fit me as well. Please guide how i can integrate it in javaScript.
Thanks

**Comment by atiqq122** [comment]
@chyccs  waiting for your response. as you mentioned that you have some materials in javascript, thats why willing to to do it with javascript.
Thanls
