### ISSUE TITLE
Dots type BLOB

### ISSUE THREAD

**Issue by letsgocodego** [NeoSmartpen/Windows-SDK2.0#29]
Hello,

I am trying to extract coordinate and timestamp data from the dat SQLite file on a neo smartpen N2. 

My understanding is that the coordinate and timestamp data are stored in the Dots column of the Stroke table which has a data type of BLOB. I cannot figure out how to parse the BLOB to extract useful timestamp and coordinate data. I have looked through the SDK and API documentation extensively and cannot figure it out. I do see that each BLOB is 21 bytes per DotCount.

@chyccs , I see that you're active here and seem to know a lot about this SDK, could you help me parse the BLOB to extract the timestamp and coordinate data? Thank you so much for your time in reading this.

**Comment by chyccs** [comment]
Hi @letsgocodego,
I have a question about SQLite.
Where do you know(get) data in SQLite.
I need to know source of it for knowing structure of blob type

**Comment by chyccs** [comment]
Hi @letsgocodego,
I am sorry. I have no information about it. 
I can not expect accessing information of neo-notes application.
because data structure is private property of company.

I guess struct of blob
first 1 byte is type of dot.
next 4 byte is x typed float.
and next 4 byte is y typed float.
it is just my opinion.

**Comment by letsgocodego** [comment]
Ok, thank you!
